# dans src/StatusMysql.py, ajoute une fonction testable :
def check_mysql_server(host, user, password, database, port=3306, timeout=3) -> bool:
    # ... logique connexion + SELECT 1 + retours True/False ...
    ...